apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
  namespace: case-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
        - name: hello
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          ports:
            - containerPort: 8000
          env:
            - name: "HW_RESPONSE"
              value: "[\"Astrud Gilberto (Bahia, Brazil)\",\"Miles Davis (Alton, Illinois)\"]"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-v2
  namespace: case-study
  labels:
    app: hello
    version: v2
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: hello
    version: v2
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: hello-v2
  namespace: case-study
spec:
  meshName: hello
  listeners:
    - portMapping:
        port: 8000
        protocol: http
  serviceDiscovery:
    dns:
      hostName: hello-v2.case-study.svc.cluster.local
