---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  annotations:
    flux.weave.works/automated: "true"
data:
  GF_SERVER_ROOT_URL: https://grafana.vogorental.com
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: prod-infra-db.ckk1ooeb2hvi.ap-south-1.rds.amazonaws.com
  GF_DATABASE_NAME: grafana
  GF_DATABASE_USER: infra_admin
  GF_DATABASE_PASSWORD: JvKmOKsNJy79iIKsaGcq18A
  GF_AUTH_GOOGLE_ENABLED: "true"
  GF_AUTH_GOOGLE_ALLOW_SIGN_UP: "true"
  GF_AUTH_GOOGLE_CLIENT_ID: 1029074587610-ukqp9od7m1tsp72vhji1n9d8nrj3d3ud.apps.googleusercontent.com
  GF_AUTH_GOOGLE_CLIENT_SECRET: gj2Z0q1ORIAhiI6anurRRVmL
  GF_AUTH_GOOGLE_SCOPES: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
  GF_AUTH_GOOGLE_AUTH_URL: https://accounts.google.com/o/oauth2/auth
  GF_AUTH_GOOGLE_TOKEN_URL: https://accounts.google.com/o/oauth2/token
  GF_AUTH_GOOGLE_ALLOWED_DOMAINS: vogo.in
  GF_INSTALL_PLUGINS: "grafana-piechart-panel,raintank-worldping-app,grafana-kubernetes-app"
